version: '3.1'

networks:
  lared:
    driver: bridge

services:
  members_producer:
    container_name: members_producer
    build: ./server/Members/producer
    depends_on:
       - members_consumer
    # volumes:
    #    - './server/api:/usr/src/app'
    networks:
       - lared
    ports:
      - "3000:3000"
        
  members_consumer:
    container_name: members_consumer
    build: ./server/Members/consumer
    networks:
      - lared
    # volumes:
    #   - ./server/error:/usr/src/app

    ports:
      - "8000:8000"

  sale_producer:
    container_name: sale_producer
    build: ./server/Ventas/producer
    networks:
      - lared
    depends_on:
       - sales_consumer
    # volumes:
    #   - ./server/error:/usr/src/app

    ports:
      - "3001:3000"

  sales_consumer:
    container_name: sales_consumer
    build: ./server/Ventas/consumer
    networks:
      - lared
    # volumes:
    #   - ./server/error:/usr/src/app

    ports:
      - "8001:8000"

  stock_consumer:
    container_name: stock_consumer
    build: ./server/Stock/consumer
    networks:
      - lared
    # volumes:
    #   - ./server/error:/usr/src/app

    ports:
      - "8002:8000"
  
  zookeeper:
    container_name: elzookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - lared
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    
  kafka:
    container_name: elkafka
    image: 'bitnami/kafka:latest'
    networks:
     - lared
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
