version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


serverproducer:
    build: './Productor'
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST_IP=kafka
    ports:
      - "3000:3000"

consumers:
    build: './Consumidor'
    depends_on:
      - serverproducer
    environment:
      - KAFKA_HOST_IP=kafka